[package]
name = "ckb-analyzer"
version = "0.0.5"
license = "MIT"
authors = ["keroro <keroroxx520@gmail.com>"]
edition = "2018"
description = "ckb-analyzer analyzes kinds of data sources and upload the results into PostgreSQL"
homepage = "https://github.com/keroro520/ckb-analyzer"

[dependencies]
ckb-suite-rpc = { path = "ckb-suite-rpc", version = "0.0.3" }
ckb-network = { version = "0.39.1" }
ckb-util = { version = "0.39.1" }
ckb-sync = { version = "0.39.1" }
ckb-logger = { version = "0.39.1" }
ckb-build-info = { version = "0.39.1" }
ckb-types = { version = "0.39.1" }
ckb-app-config = { version = "0.39.1" }
ckb-async-runtime = { version = "0.39.1" }

tokio = { version = "1.2.0", features = ["full"] }
crossbeam = { version = "0.8.0" }
chrono = { version = "0.4.19" }
toml = { version = "0.5" }
gethostname = { version = "0.2.1" }
serde = { version = "1.0.117", features = [ "derive" ] }
serde_json = { version = "1.0.59" }
case_style = { version = "0.2.1" }
tynm = { version = "0.1.6" }
jsonrpc-core = { version = "15.1" }
jsonrpc-derive = { version = "15.1" }
jsonrpc-tcp-server = { version = "15.1" }
jsonrpc-ws-server = { version = "15.1" }
jsonrpc-server-utils = { version = "15.1" }
jsonrpc-pubsub = { version = "15.1" }
jsonrpc-core-client = { version = "15.1" }
jsonrpc-client-transports = { version = "15.1" }
logwatcher = { version = "0.1.1" }
regex = { version = "1" }
log = { version = "0.4.11" }
simple_logger = { version = "1.11.0", default-features = false }
tentacle-multiaddr = { version = "0.2" }
tokio-postgres = { version = "0.7.0", features = ["with-chrono-0_4", "runtime"] }
ipinfo = { git = "https://github.com/keroro520/rust-ipinfo", branch = "hostname-optional" }

[workspace]
members = [
    "ckb-suite-rpc"
]
