version: '3'

services:
  postgresql:
    container_name: ckb-analyzer-postgresql
    image: timescale/timescaledb:latest-pg12
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql/var/lib/postgresql/data:/var/lib/postgresql/data"

  grafana:
    container_name: ckb-analyzer-grafana
    image: grafana/grafana:latest
    user: root
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/etc/grafana:/etc/grafana
      - ./grafana/var/lib/grafana:/var/lib/grafana
    depends_on:
      - postgresql
